
# Gem::Specification for Campaign_monitor-0.1.1
# Originally generated by Echoe

--- !ruby/object:Gem::Specification 
name: campaign_monitor
version: !ruby/object:Gem::Version 
  version: 0.1.1
platform: ruby
authors: 
- Jordan Brock
autorequire: 
bindir: bin

date: 2008-08-16 00:00:00 -07:00
default_executable: 
dependencies: 
- !ruby/object:Gem::Dependency 
  name: echoe
  type: :development
  version_requirement: 
  version_requirements: !ruby/object:Gem::Requirement 
    requirements: 
    - - ">="
      - !ruby/object:Gem::Version 
        version: "0"
    version: 
description: A simple wrapper class that provides basic access to the Campaign Monitor API
email: jordan@spintech.com.au
executables: []

extensions: []

extra_rdoc_files: 
- LICENSE
- CHANGELOG
- TODO
- lib/campaign_monitor.rb
- lib/campaign_monitor/campaign.rb
- lib/campaign_monitor/list.rb
- lib/campaign_monitor/client.rb
- lib/campaign_monitor/result.rb
- lib/campaign_monitor/subscriber.rb
- README.rdoc
files: 
- LICENSE
- CHANGELOG
- init.rb
- Rakefile
- test/campaign_monitor_test.rb
- TODO
- lib/campaign_monitor.rb
- lib/campaign_monitor/campaign.rb
- lib/campaign_monitor/list.rb
- lib/campaign_monitor/client.rb
- lib/campaign_monitor/result.rb
- lib/campaign_monitor/subscriber.rb
- README.rdoc
- install.rb
- campaign-monitor-ruby.gemspec
- Manifest
has_rdoc: true
homepage: http://spintech.com.au/projects/plugins/campaign_monitor
post_install_message: 
rdoc_options: 
- --line-numbers
- --inline-source
- --title
- Campaign-monitor-ruby
- --main
- README.rdoc
require_paths: 
- lib
required_ruby_version: !ruby/object:Gem::Requirement 
  requirements: 
  - - ">="
    - !ruby/object:Gem::Version 
      version: "0"
  version: 
required_rubygems_version: !ruby/object:Gem::Requirement 
  requirements: 
  - - "="
    - !ruby/object:Gem::Version 
      version: "1.2"
  version: 
requirements: []

rubyforge_project: campaignmonitor
rubygems_version: 1.2.0
specification_version: 2
summary: Provides access to the Campaign Monitor API
test_files: 
- test/campaign_monitor_test.rb
